db:
  host: ""
  port: ""
  user: ""
  password: ""
  database: ""

mac:
  heroku:
    inference_key: ""
  openai_key: ""

#Salesforce configurations
sfdc:
  url: "http://login.salesforce.com/services/Soap/u/64.0"
  token: ""
  password: ""
  account: ""